services:
  db:
    build:
      context: .
      target: db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: inks_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      target: app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_root_password
      DB_NAME: inks_db

volumes:
  db_data:

