pipeline {
  agent any
  parameters {
    gitParameter(
      name: 'TAG_TO_DEPLOY',
      type: 'PT_TAG',
      defaultValue: '',
      description: 'Select a Git tag to deploy',
      branch: '',
      sortMode: 'DESCENDING_SMART',
      selectedValue: 'TOP',
      useRepository: 'https://github.com/omareldemerdash/InksManager.git'
    )
  }
  environment {
        CREDENTIALS = credentials('dockerhub')
        AWS_DEFAULT_REGION = 'us-east-1'
  }
  stages {
     stage('Validate Tag') {
      steps {
        script {
          if (!params.TAG_TO_DEPLOY?.trim()) {
            error("❌ You must select a Git tag to deploy.")
          }
        }
      }
    }
     stage('Checkout Code at Tag') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: "refs/tags/${params.TAG_TO_DEPLOY}"]],
          userRemoteConfigs: [[url: 'https://github.com/omareldemerdash/InksManager.git']] // update this
        ])
        echo "✅ Checked out tag: ${params.TAG_TO_DEPLOY}"
      }
    }
  
  }
}
